// Code generated from src/main/kotlin/fr/gouv/agora/domain/{Department,Territoire}.kt; DO NOT EDIT.
// Enum declaration order is preserved (it drives JSON output order and firstOrNull lookups).

package domain

// Department is the enum fr.gouv.agora.domain.Department.
type Department struct {
	Name    string
	Ordinal int
}

// Departments lists Department.values() in declaration order.
var Departments = []*Department{
	{Name: "AIN_01", Ordinal: 0},
	{Name: "AISNE_02", Ordinal: 1},
	{Name: "ALLIER_03", Ordinal: 2},
	{Name: "ALPESDEHAUTEPROVENCE_04", Ordinal: 3},
	{Name: "HAUTESALPES_05", Ordinal: 4},
	{Name: "ALPESMARITIMES_06", Ordinal: 5},
	{Name: "ARDECHE_07", Ordinal: 6},
	{Name: "ARDENNES_08", Ordinal: 7},
	{Name: "ARIEGE_09", Ordinal: 8},
	{Name: "AUBE_10", Ordinal: 9},
	{Name: "AUDE_11", Ordinal: 10},
	{Name: "AVEYRON_12", Ordinal: 11},
	{Name: "BOUCHESDURHONE_13", Ordinal: 12},
	{Name: "CALVADOS_14", Ordinal: 13},
	{Name: "CANTAL_15", Ordinal: 14},
	{Name: "CHARENTE_16", Ordinal: 15},
	{Name: "CHARENTEMARITIME_17", Ordinal: 16},
	{Name: "CHER_18", Ordinal: 17},
	{Name: "CORREZE_19", Ordinal: 18},
	{Name: "CORSEDUSUD_2A", Ordinal: 19},
	{Name: "HAUTECORSE_2B", Ordinal: 20},
	{Name: "COTEDOR_21", Ordinal: 21},
	{Name: "COTESDARMOR_22", Ordinal: 22},
	{Name: "CREUSE_23", Ordinal: 23},
	{Name: "DORDOGNE_24", Ordinal: 24},
	{Name: "DOUBS_25", Ordinal: 25},
	{Name: "DROME_26", Ordinal: 26},
	{Name: "EURE_27", Ordinal: 27},
	{Name: "EUREETLOIR_28", Ordinal: 28},
	{Name: "FINISTERE_29", Ordinal: 29},
	{Name: "GARD_30", Ordinal: 30},
	{Name: "HAUTEGARONNE_31", Ordinal: 31},
	{Name: "GERS_32", Ordinal: 32},
	{Name: "GIRONDE_33", Ordinal: 33},
	{Name: "HERAULT_34", Ordinal: 34},
	{Name: "ILLEETVILAINE_35", Ordinal: 35},
	{Name: "INDRE_36", Ordinal: 36},
	{Name: "INDREETLOIRE_37", Ordinal: 37},
	{Name: "ISERE_38", Ordinal: 38},
	{Name: "JURA_39", Ordinal: 39},
	{Name: "LANDES_40", Ordinal: 40},
	{Name: "LOIRETCHER_41", Ordinal: 41},
	{Name: "LOIRE_42", Ordinal: 42},
	{Name: "HAUTELOIRE_43", Ordinal: 43},
	{Name: "LOIREATLANTIQUE_44", Ordinal: 44},
	{Name: "LOIRET_45", Ordinal: 45},
	{Name: "LOT_46", Ordinal: 46},
	{Name: "LOTETGARONNE_47", Ordinal: 47},
	{Name: "LOZERE_48", Ordinal: 48},
	{Name: "MAINEETLOIRE_49", Ordinal: 49},
	{Name: "MANCHE_50", Ordinal: 50},
	{Name: "MARNE_51", Ordinal: 51},
	{Name: "HAUTEMARNE_52", Ordinal: 52},
	{Name: "MAYENNE_53", Ordinal: 53},
	{Name: "MEURTHEETMOSELLE_54", Ordinal: 54},
	{Name: "MEUSE_55", Ordinal: 55},
	{Name: "MORBIHAN_56", Ordinal: 56},
	{Name: "MOSELLE_57", Ordinal: 57},
	{Name: "NIEVRE_58", Ordinal: 58},
	{Name: "NORD_59", Ordinal: 59},
	{Name: "OISE_60", Ordinal: 60},
	{Name: "ORNE_61", Ordinal: 61},
	{Name: "PASDECALAIS_62", Ordinal: 62},
	{Name: "PUYDEDOME_63", Ordinal: 63},
	{Name: "PYRENEESATLANTIQUES_64", Ordinal: 64},
	{Name: "HAUTESPYRENEES_65", Ordinal: 65},
	{Name: "PYRENEESORIENTALES_66", Ordinal: 66},
	{Name: "BASRHIN_67", Ordinal: 67},
	{Name: "HAUTRHIN_68", Ordinal: 68},
	{Name: "RHONE_69", Ordinal: 69},
	{Name: "HAUTESAONE_70", Ordinal: 70},
	{Name: "SAONEETLOIRE_71", Ordinal: 71},
	{Name: "SARTHE_72", Ordinal: 72},
	{Name: "SAVOIE_73", Ordinal: 73},
	{Name: "HAUTESAVOIE_74", Ordinal: 74},
	{Name: "PARIS_75", Ordinal: 75},
	{Name: "SEINEMARITIME_76", Ordinal: 76},
	{Name: "SEINEETMARNE_77", Ordinal: 77},
	{Name: "YVELINES_78", Ordinal: 78},
	{Name: "DEUXSEVRES_79", Ordinal: 79},
	{Name: "SOMME_80", Ordinal: 80},
	{Name: "TARN_81", Ordinal: 81},
	{Name: "TARNETGARONNE_82", Ordinal: 82},
	{Name: "VAR_83", Ordinal: 83},
	{Name: "VAUCLUSE_84", Ordinal: 84},
	{Name: "VENDEE_85", Ordinal: 85},
	{Name: "VIENNE_86", Ordinal: 86},
	{Name: "HAUTEVIENNE_87", Ordinal: 87},
	{Name: "VOSGES_88", Ordinal: 88},
	{Name: "YONNE_89", Ordinal: 89},
	{Name: "TERRITOIREDEBELFORT_90", Ordinal: 90},
	{Name: "ESSONNE_91", Ordinal: 91},
	{Name: "HAUTSDESEINE_92", Ordinal: 92},
	{Name: "SEINESAINTDENIS_93", Ordinal: 93},
	{Name: "VALDEMARNE_94", Ordinal: 94},
	{Name: "VALDOISE_95", Ordinal: 95},
	{Name: "GUADELOUPE_971", Ordinal: 96},
	{Name: "MARTINIQUE_972", Ordinal: 97},
	{Name: "GUYANE_973", Ordinal: 98},
	{Name: "LAREUNION_974", Ordinal: 99},
	{Name: "MAYOTTE_976", Ordinal: 100},
	{Name: "NOUVELLECALEDONIE_988", Ordinal: 101},
	{Name: "POLYNESIEFRANCAISE_987", Ordinal: 102},
	{Name: "SAINTBARTHELEMY_977", Ordinal: 103},
	{Name: "SAINTMARTIN_978", Ordinal: 104},
	{Name: "SAINTPIERREETMIQUELON_975", Ordinal: 105},
	{Name: "TERRESAUSTRALESETANTARCTIQUESFRANCAISES_984", Ordinal: 106},
	{Name: "WALLISETFUTUNA_986", Ordinal: 107},
	{Name: "ETRANGER_99", Ordinal: 108},
}

// Pays is Territoire.Pays.
type Pays struct{ Name, value string }

// PaysValues lists Territoire.Pays.values().
var PaysValues = []*Pays{
	{Name: "FRANCE", value: "France"},
	{Name: "HORS_DE_FRANCE", value: "Français de l'étranger"},
}

// Departement is Territoire.Departement.
type Departement struct{ Name, value, CodePostal string }

// DepartementValues lists Territoire.Departement.values().
var DepartementValues = []*Departement{
	{Name: "AIN", value: "Ain", CodePostal: "01"},
	{Name: "ALLIER", value: "Allier", CodePostal: "03"},
	{Name: "ARDECHE", value: "Ardèche", CodePostal: "07"},
	{Name: "CANTAL", value: "Cantal", CodePostal: "15"},
	{Name: "DROME", value: "Drôme", CodePostal: "26"},
	{Name: "ISERE", value: "Isère", CodePostal: "38"},
	{Name: "LOIRE", value: "Loire", CodePostal: "42"},
	{Name: "HAUTE_LOIRE", value: "Haute-Loire", CodePostal: "43"},
	{Name: "PUY_DE_DOME", value: "Puy-de-Dôme", CodePostal: "63"},
	{Name: "RHONE", value: "Rhône", CodePostal: "69"},
	{Name: "SAVOIE", value: "Savoie", CodePostal: "73"},
	{Name: "HAUTE_SAVOIE", value: "Haute-Savoie", CodePostal: "74"},
	{Name: "COTE_D_OR", value: "Côte-d’Or", CodePostal: "21"},
	{Name: "DOUBS", value: "Doubs", CodePostal: "25"},
	{Name: "JURA", value: "Jura", CodePostal: "39"},
	{Name: "NIEVRE", value: "Nièvre", CodePostal: "58"},
	{Name: "HAUTE_SAONE", value: "Haute-Saône", CodePostal: "70"},
	{Name: "SAONE_ET_LOIRE", value: "Saône-et-Loire", CodePostal: "71"},
	{Name: "YONNE", value: "Yonne", CodePostal: "89"},
	{Name: "TERRITOIRE_DE_BELFORT", value: "Territoire de Belfort", CodePostal: "90"},
	{Name: "COTES_D_ARMOR", value: "Côtes-d’Armor", CodePostal: "22"},
	{Name: "FINISTERE", value: "Finistère", CodePostal: "29"},
	{Name: "ILLE_ET_VILAINE", value: "Ille-et-Vilaine", CodePostal: "35"},
	{Name: "MORBIHAN", value: "Morbihan", CodePostal: "56"},
	{Name: "CHER", value: "Cher", CodePostal: "18"},
	{Name: "EURE_ET_LOIR", value: "Eure-et-Loir", CodePostal: "28"},
	{Name: "INDRE", value: "Indre", CodePostal: "36"},
	{Name: "INDRE_ET_LOIRE", value: "Indre-et-Loire", CodePostal: "37"},
	{Name: "LOIR_ET_CHER", value: "Loir-et-Cher", CodePostal: "41"},
	{Name: "LOIRET", value: "Loiret", CodePostal: "45"},
	{Name: "CORSE_DU_SUD", value: "Corse-du-Sud", CodePostal: "2A"},
	{Name: "HAUTE_CORSE", value: "Haute-Corse", CodePostal: "2B"},
	{Name: "ARDENNES", value: "Ardennes", CodePostal: "08"},
	{Name: "AUBE", value: "Aube", CodePostal: "10"},
	{Name: "MARNE", value: "Marne", CodePostal: "51"},
	{Name: "HAUTE_MARNE", value: "Haute-Marne", CodePostal: "52"},
	{Name: "MEURTHE_ET_MOSELLE", value: "Meurthe-et-Moselle", CodePostal: "54"},
	{Name: "MEUSE", value: "Meuse", CodePostal: "55"},
	{Name: "MOSELLE", value: "Moselle", CodePostal: "57"},
	{Name: "BAS_RHIN", value: "Bas-Rhin", CodePostal: "67"},
	{Name: "HAUT_RHIN", value: "Haut-Rhin", CodePostal: "68"},
	{Name: "VOSGES", value: "Vosges", CodePostal: "88"},
	{Name: "AISNE", value: "Aisne", CodePostal: "02"},
	{Name: "NORD", value: "Nord", CodePostal: "59"},
	{Name: "OISE", value: "Oise", CodePostal: "60"},
	{Name: "PAS_DE_CALAIS", value: "Pas-de-Calais", CodePostal: "62"},
	{Name: "SOMME", value: "Somme", CodePostal: "80"},
	{Name: "PARIS", value: "Paris", CodePostal: "75"},
	{Name: "SEINE_ET_MARNE", value: "Seine-et-Marne", CodePostal: "77"},
	{Name: "YVELINES", value: "Yvelines", CodePostal: "78"},
	{Name: "ESSONNE", value: "Essonne", CodePostal: "91"},
	{Name: "HAUTS_DE_SEINE", value: "Hauts-de-Seine", CodePostal: "92"},
	{Name: "SEINE_SAINT_DENIS", value: "Seine-Saint-Denis", CodePostal: "93"},
	{Name: "VAL_DE_MARNE", value: "Val-de-Marne", CodePostal: "94"},
	{Name: "VAL_D_OISE", value: "Val-d’Oise", CodePostal: "95"},
	{Name: "EURE", value: "Eure", CodePostal: "27"},
	{Name: "MANCHE", value: "Manche", CodePostal: "50"},
	{Name: "ORNE", value: "Orne", CodePostal: "61"},
	{Name: "SEINE_MARITIME", value: "Seine-Maritime", CodePostal: "76"},
	{Name: "CHARENTE", value: "Charente", CodePostal: "16"},
	{Name: "CHARENTE_MARITIME", value: "Charente-Maritime", CodePostal: "17"},
	{Name: "CORREZE", value: "Corrèze", CodePostal: "19"},
	{Name: "CREUSE", value: "Creuse", CodePostal: "23"},
	{Name: "DORDOGNE", value: "Dordogne", CodePostal: "24"},
	{Name: "GIRONDE", value: "Gironde", CodePostal: "33"},
	{Name: "LANDES", value: "Landes", CodePostal: "40"},
	{Name: "LOT_ET_GARONNE", value: "Lot-et-Garonne", CodePostal: "47"},
	{Name: "CALVADOS", value: "Calvados", CodePostal: "14"},
	{Name: "PYRENEES_ATLANTIQUES", value: "Pyrénées-Atlantiques", CodePostal: "64"},
	{Name: "DEUX_SEVRES", value: "Deux-Sèvres", CodePostal: "79"},
	{Name: "VIENNE", value: "Vienne", CodePostal: "86"},
	{Name: "HAUTE_VIENNE", value: "Haute-Vienne", CodePostal: "87"},
	{Name: "ARIEGE", value: "Ariège", CodePostal: "09"},
	{Name: "AUDE", value: "Aude", CodePostal: "11"},
	{Name: "AVEYRON", value: "Aveyron", CodePostal: "12"},
	{Name: "GARD", value: "Gard", CodePostal: "30"},
	{Name: "HAUTE_GARONNE", value: "Haute-Garonne", CodePostal: "31"},
	{Name: "GERS", value: "Gers", CodePostal: "32"},
	{Name: "HERAULT", value: "Hérault", CodePostal: "34"},
	{Name: "LOT", value: "Lot", CodePostal: "46"},
	{Name: "LOZERE", value: "Lozère", CodePostal: "48"},
	{Name: "HAUTES_PYRENEES", value: "Hautes-Pyrénées", CodePostal: "65"},
	{Name: "PYRENEES_ORIENTALES", value: "Pyrénées-Orientales", CodePostal: "66"},
	{Name: "TARN", value: "Tarn", CodePostal: "81"},
	{Name: "TARN_ET_GARONNE", value: "Tarn-et-Garonne", CodePostal: "82"},
	{Name: "LOIRE_ATLANTIQUE", value: "Loire-Atlantique", CodePostal: "44"},
	{Name: "MAINE_ET_LOIRE", value: "Maine-et-Loire", CodePostal: "49"},
	{Name: "MAYENNE", value: "Mayenne", CodePostal: "53"},
	{Name: "SARTHE", value: "Sarthe", CodePostal: "72"},
	{Name: "VENDEE", value: "Vendée", CodePostal: "85"},
	{Name: "ALPES_DE_HAUTE_PROVENCE", value: "Alpes-de-Haute-Provence", CodePostal: "04"},
	{Name: "HAUTES_ALPES", value: "Hautes-Alpes", CodePostal: "05"},
	{Name: "ALPES_MARITIMES", value: "Alpes-Maritimes", CodePostal: "06"},
	{Name: "BOUCHES_DU_RHONE", value: "Bouches-du-Rhône", CodePostal: "13"},
	{Name: "VAR", value: "Var", CodePostal: "83"},
	{Name: "VAUCLUSE", value: "Vaucluse", CodePostal: "84"},
	{Name: "GUADELOUPE", value: "Guadeloupe", CodePostal: "971"},
	{Name: "MARTINIQUE", value: "Martinique", CodePostal: "972"},
	{Name: "GUYANE", value: "Guyane", CodePostal: "973"},
	{Name: "LA_REUNION", value: "La Réunion", CodePostal: "974"},
	{Name: "MAYOTTE", value: "Mayotte", CodePostal: "976"},
	{Name: "SAINT_PIERRE_ET_MIQUELON", value: "Saint-Pierre-et-Miquelon", CodePostal: "975"},
	{Name: "SAINT_BARTHELEMY", value: "Saint-Barthélémy", CodePostal: "977"},
	{Name: "SAINT_MARTIN", value: "Saint-Martin", CodePostal: "978"},
	{Name: "TERRES_AUSTRALES_ET_ANTARCTIQUES_FRANCAISES", value: "Terres australes et antarctiques françaises", CodePostal: "984"},
	{Name: "WALLIS_ET_FUTUNA", value: "Wallis-et-Futuna", CodePostal: "986"},
	{Name: "POLYNESIE_FRANCAISE", value: "Polynésie française", CodePostal: "987"},
	{Name: "NOUVELLE_CALEDONIE", value: "Nouvelle-Calédonie", CodePostal: "988"},
}

// Region is Territoire.Region.
type Region struct {
	Name         string
	value        string
	Departements []*Departement
}

// RegionValues lists Territoire.Region.values().
var RegionValues []*Region

func init() {
	byName := map[string]*Departement{}
	for _, d := range DepartementValues {
		byName[d.Name] = d
	}
	dep := func(names ...string) []*Departement {
		out := make([]*Departement, len(names))
		for i, n := range names {
			out[i] = byName[n]
		}
		return out
	}
	RegionValues = []*Region{
		{Name: "AUVERGNE_RHONE_ALPES", value: "Auvergne-Rhône-Alpes", Departements: dep("AIN", "ALLIER", "ARDECHE", "CANTAL", "DROME", "ISERE", "LOIRE", "HAUTE_LOIRE", "PUY_DE_DOME", "RHONE", "SAVOIE", "HAUTE_SAVOIE")},
		{Name: "BOURGOGNE_FRANCHE_COMTE", value: "Bourgogne-Franche-Comté", Departements: dep("COTE_D_OR", "DOUBS", "JURA", "NIEVRE", "HAUTE_SAONE", "SAONE_ET_LOIRE", "YONNE", "TERRITOIRE_DE_BELFORT")},
		{Name: "BRETAGNE", value: "Bretagne", Departements: dep("COTES_D_ARMOR", "FINISTERE", "ILLE_ET_VILAINE", "MORBIHAN")},
		{Name: "CENTRE_VAL_DE_LOIRE", value: "Centre-Val de Loire", Departements: dep("CHER", "EURE_ET_LOIR", "INDRE", "INDRE_ET_LOIRE", "LOIR_ET_CHER", "LOIRET")},
		{Name: "CORSE", value: "Corse", Departements: dep("CORSE_DU_SUD", "HAUTE_CORSE")},
		{Name: "GRAND_EST", value: "Grand Est", Departements: dep("ARDENNES", "AUBE", "MARNE", "HAUTE_MARNE", "MEURTHE_ET_MOSELLE", "MEUSE", "MOSELLE", "BAS_RHIN", "HAUT_RHIN", "VOSGES")},
		{Name: "HAUTS_DE_FRANCE", value: "Hauts-de-France", Departements: dep("AISNE", "NORD", "OISE", "PAS_DE_CALAIS", "SOMME")},
		{Name: "ILE_DE_FRANCE", value: "Ile-de-France", Departements: dep("PARIS", "SEINE_ET_MARNE", "YVELINES", "ESSONNE", "HAUTS_DE_SEINE", "SEINE_SAINT_DENIS", "VAL_DE_MARNE", "VAL_D_OISE")},
		{Name: "NORMANDIE", value: "Normandie", Departements: dep("CALVADOS", "EURE", "MANCHE", "ORNE", "SEINE_MARITIME")},
		{Name: "NOUVELLE_AQUITAINE", value: "Nouvelle-Aquitaine", Departements: dep("CHARENTE", "CHARENTE_MARITIME", "CORREZE", "CREUSE", "DORDOGNE", "GIRONDE", "LANDES", "LOT_ET_GARONNE", "PYRENEES_ATLANTIQUES", "DEUX_SEVRES", "VIENNE", "HAUTE_VIENNE")},
		{Name: "OCCITANIE", value: "Occitanie", Departements: dep("ARIEGE", "AUDE", "AVEYRON", "GARD", "HAUTE_GARONNE", "GERS", "HERAULT", "LOT", "LOZERE", "HAUTES_PYRENEES", "PYRENEES_ORIENTALES", "TARN", "TARN_ET_GARONNE")},
		{Name: "PAYS_DE_LA_LOIRE", value: "Pays de la Loire", Departements: dep("LOIRE_ATLANTIQUE", "MAINE_ET_LOIRE", "MAYENNE", "SARTHE", "VENDEE")},
		{Name: "PROVENCE_ALPES_COTE_D_AZUR", value: "Provence Alpes Côte d’Azur", Departements: dep("ALPES_DE_HAUTE_PROVENCE", "HAUTES_ALPES", "ALPES_MARITIMES", "BOUCHES_DU_RHONE", "VAR", "VAUCLUSE")},
		{Name: "OUTRE_MER", value: "Outre-mer", Departements: dep("GUADELOUPE", "MARTINIQUE", "GUYANE", "LA_REUNION", "MAYOTTE", "SAINT_PIERRE_ET_MIQUELON", "SAINT_BARTHELEMY", "SAINT_MARTIN", "TERRES_AUSTRALES_ET_ANTARCTIQUES_FRANCAISES", "WALLIS_ET_FUTUNA", "POLYNESIE_FRANCAISE", "NOUVELLE_CALEDONIE")},
	}
}
