// Command gencharsets generates internal/javacompat/charsets_gen.go from the
// JVM of the reference (Charset.availableCharsets()): every charset name and
// alias, and the exact decoding table of every single-byte charset (each byte
// decoded alone by the JVM, CodingErrorAction.REPLACE).
//
//	PARITY_ORACLE=1 go run ./internal/javacompat/tools/gencharsets > internal/javacompat/charsets_gen.go
package main

import (
	"encoding/base64"
	"fmt"
	"os"
	"sort"
	"strings"

	"agora/parity/oracle"
)

type cs struct {
	Name    string   `json:"name"`
	Aliases []string `json:"aliases"`
}

type decoded struct {
	Name  string   `json:"name"`
	UTF16 []uint16 `json:"utf16"`
	Error string   `json:"error"`
}

func decode(name string, b []byte) decoded {
	var d decoded
	if err := oracle.Call("javaCharsetDecode", map[string]any{"charset": name, "b64": base64.StdEncoding.EncodeToString(b)}, &d); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	return d
}

func main() {
	var all []cs
	if err := oracle.Call("javaCharsets", nil, &all); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	aliases := map[string]string{}
	tables := map[string][256]uint16{}
	for _, c := range all {
		aliases[strings.ToLower(c.Name)] = c.Name
		for _, a := range c.Aliases {
			aliases[strings.ToLower(a)] = c.Name
		}
		if strings.HasPrefix(c.Name, "UTF-") || c.Name == "CESU-8" {
			continue // multi-byte: each lone high byte is malformed, which only looks single-byte
		}
		var block [256]byte
		for i := range block {
			block[i] = byte(i)
		}
		d := decode(c.Name, block[:])
		if d.Error != "" || len(d.UTF16) != 256 {
			continue
		}
		var tab [256]uint16
		single := true
		for i := 0; i < 256 && single; i++ {
			one := decode(c.Name, []byte{byte(i)})
			if len(one.UTF16) != 1 || one.UTF16[0] != d.UTF16[i] {
				single = false
			}
			tab[i] = d.UTF16[i]
		}
		if single {
			tables[c.Name] = tab
		}
	}
	var b strings.Builder
	b.WriteString("// Code generated by internal/javacompat/tools/gencharsets from the reference JVM; DO NOT EDIT.\n\npackage javacompat\n\n")
	b.WriteString("// javaCharsetNames maps every lower-cased charset name and alias of the JVM to its canonical name.\nvar javaCharsetNames = map[string]string{\n")
	keys := make([]string, 0, len(aliases))
	for k := range aliases {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	for _, k := range keys {
		fmt.Fprintf(&b, "\t%q: %q,\n", k, aliases[k])
	}
	b.WriteString("}\n\n// javaSingleByte holds the 256 UTF-16 units each byte decodes to, for every single-byte charset.\nvar javaSingleByte = map[string]*[256]uint16{\n")
	names := make([]string, 0, len(tables))
	for k := range tables {
		names = append(names, k)
	}
	sort.Strings(names)
	for _, n := range names {
		t := tables[n]
		fmt.Fprintf(&b, "\t%q: {", n)
		for i, u := range t {
			if i%16 == 0 {
				b.WriteString("\n\t\t")
			}
			fmt.Fprintf(&b, "0x%04x, ", u)
		}
		b.WriteString("\n\t},\n")
	}
	b.WriteString("}\n")
	fmt.Print(b.String())
	fmt.Fprintf(os.Stderr, "%d charsets, %d names, %d single-byte tables\n", len(all), len(aliases), len(tables))
}
