#!/usr/bin/env python3
"""Generates elements_gen.go and entities_gen.go from the OWASP java-html-sanitizer 20220608.1 sources.

    python3 -I gen_tables.py <dir with org/owasp/html/*.java> <output dir>

Inputs: HtmlElementTablesCanned.java (element names, containment matrix, resumable set, text content
model, implied elements) and HtmlEntities.java (the WHATWG named character references).
"""
import re
import sys
import os


def java_ints(body):
    return [int(x) for x in re.findall(r"-?\d+", body)]


def words(vals):
    # Java int -> unsigned 32 bit word.
    return [v & 0xFFFFFFFF for v in vals]


def go_words(name, vals, per_line=8):
    out = ["var %s = [...]uint32{" % name]
    ws = words(vals)
    for i in range(0, len(ws), per_line):
        out.append("\t" + ", ".join("0x%08x" % w for w in ws[i:i + per_line]) + ",")
    out.append("}")
    return "\n".join(out)


def gen_elements(src_dir, out_dir):
    src = open(os.path.join(src_dir, "org/owasp/html/HtmlElementTablesCanned.java"), encoding="utf-8").read()

    m = re.search(r"new HtmlElementTables\.HtmlElementNames\(\s*new String\[\] \{(.*?)\}", src, re.S)
    names = re.findall(r'"([^"]*)"', m.group(1))
    n = len(names)
    assert n == 145, n

    def matrix(var):
        m = re.search(var + r" = new HtmlElementTables\.DenseElementBinaryMatrix\(\s*HtmlElementTables\.unpack\(new int\[\] \{(.*?)\}, (\d+)\)", src, re.S)
        assert int(m.group(2)) == n * n
        vals = java_ints(m.group(1))
        assert len(vals) == (n * n + 31) // 32, len(vals)
        return vals

    can_contain = matrix("canContain")

    m = re.search(r"resumable = new HtmlElementTables\.DenseElementSet\(\s*HtmlElementTables\.unpack\(new int\[\] \{(.*?)\}, (\d+)\)", src, re.S)
    resumable = java_ints(m.group(1))
    assert int(m.group(2)) == n and len(resumable) == (n + 31) // 32

    m = re.search(r"textContentModel = new HtmlElementTables\.TextContentModel\(\s*new byte\[\] \{(.*?)\}", src, re.S)
    tcm = [int(x) for x in re.findall(r"\(byte\)(-?\d+)", m.group(1))]
    assert len(tcm) == n
    tcm = [v & 0xFF for v in tcm]

    # impliedElements: int[][][] with null rows; row index = element a, each row: {b, implied...}.
    m = re.search(r"impliedElements = new HtmlElementTables\.SparseElementMultitable\(\s*new int\[\]\[\]\[\] \{(.*?)\n      \}\n    \);", src, re.S)
    body = m.group(1)
    tokens = re.findall(r"null|\{|\}|-?\d+", body)
    pos = 0
    # top level: list of entries separated by commas; each is null or { {ints}, {ints} ... }
    rows = []
    depth = 0
    cur_row = None
    cur_list = None
    for t in tokens:
        if t == "null":
            if depth == 0:
                rows.append(None)
        elif t == "{":
            depth += 1
            if depth == 1:
                cur_row = []
            elif depth == 2:
                cur_list = []
        elif t == "}":
            if depth == 2:
                cur_row.append(cur_list)
                cur_list = None
            elif depth == 1:
                rows.append(cur_row)
                cur_row = None
            depth -= 1
        else:
            cur_list.append(int(t))
    assert depth == 0
    assert len(rows) == n, len(rows)

    o = []
    o.append("// Code generated by tools/gen_tables.py from owasp-java-html-sanitizer-20220608.1 HtmlElementTablesCanned.java; DO NOT EDIT.\n")
    o.append("package sanitize\n")
    o.append("const nElementTypes = %d\n" % n)
    o.append("// elementNames are the canonical element names by element index (the last one, xcustom, stands for any\n// unknown element name).")
    o.append("var elementNames = [nElementTypes]string{")
    for i in range(0, n, 8):
        o.append("\t" + ", ".join('"%s"' % x for x in names[i:i + 8]) + ",")
    o.append("}\n")
    o.append("// canContainBits is the n*n containment matrix (bit a*n+b: element a can directly contain element b).")
    o.append(go_words("canContainBits", can_contain))
    o.append("")
    o.append("// resumableBits is the set of elements that are resumed after misnested inline tags.")
    o.append(go_words("resumableBits", resumable))
    o.append("")
    o.append("// textContentModel gives, per element, the TextContentModelBit mask (1 comments, 2 entities, 4 raw, 8 text, 16 unended, 32 plain text).")
    o.append("var textContentModel = [nElementTypes]uint8{")
    for i in range(0, n, 16):
        o.append("\t" + ", ".join(str(v) for v in tcm[i:i + 16]) + ",")
    o.append("}\n")
    o.append("// impliedElementTable maps (ancestor, descendant) to the elements implicitly opened between them.")
    o.append("var impliedElementTable = map[[2]int][]int{")
    for a, row in enumerate(rows):
        if row is None:
            continue
        for entry in row:
            b, rest = entry[0], entry[1:]
            o.append("\t{%d, %d}: {%s}," % (a, b, ", ".join(str(x) for x in rest)))
    o.append("}")
    open(os.path.join(out_dir, "elements_gen.go"), "w", encoding="utf-8").write("\n".join(o) + "\n")


JAVA_ESC = {'"': '"', "\\": "\\", "n": "\n", "t": "\t", "r": "\r", "'": "'"}


def parse_java_string(lit):
    """lit is the content between the quotes of a Java string literal; returns a list of UTF-16 code units."""
    units = []
    i = 0
    while i < len(lit):
        c = lit[i]
        if c == "\\":
            d = lit[i + 1]
            if d == "u":
                units.append(int(lit[i + 2:i + 6], 16))
                i += 6
                continue
            units.append(ord(JAVA_ESC[d]))
            i += 2
            continue
        cp = ord(c)
        assert cp < 0x10000
        units.append(cp)
        i += 1
    return units


def units_to_py(units):
    b = b"".join(u.to_bytes(2, "little") for u in units)
    return b.decode("utf-16-le", errors="strict")  # strict: entity values never hold lone surrogates


def gen_entities(src_dir, out_dir):
    src = open(os.path.join(src_dir, "org/owasp/html/HtmlEntities.java"), encoding="utf-8").read()
    m = re.search(r"String\[\] pairs = \{(.*?)\n    \};", src, re.S)
    lits = re.findall(r'"((?:[^"\\]|\\.)*)"', m.group(1))
    assert len(lits) % 2 == 0
    pairs = []
    for i in range(0, len(lits), 2):
        k = units_to_py(parse_java_string(lits[i]))
        v = units_to_py(parse_java_string(lits[i + 1]))
        assert k.isascii()
        pairs.append((k, v))
    assert len(set(k for k, _ in pairs)) == len(pairs)

    def go_lit(s):
        out = []
        for ch in s:
            cp = ord(ch)
            if 0x20 <= cp < 0x7F and ch not in '"\\':
                out.append(ch)
            elif cp < 0x10000:
                out.append("\\u%04x" % cp)
            else:
                out.append("\\U%08x" % cp)
        return '"' + "".join(out) + '"'

    o = []
    o.append("// Code generated by tools/gen_tables.py from owasp-java-html-sanitizer-20220608.1 HtmlEntities.java; DO NOT EDIT.\n")
    o.append("package sanitize\n")
    o.append("// entityPairs are the WHATWG named character references: name (with or without the final semicolon) and value.")
    o.append("var entityPairs = [...][2]string{")
    for k, v in pairs:
        o.append("\t{%s, %s}," % (go_lit(k), go_lit(v)))
    o.append("}")
    open(os.path.join(out_dir, "entities_gen.go"), "w", encoding="utf-8").write("\n".join(o) + "\n")


def gen_spring(props_path, out_dir):
    """HtmlCharacterEntityReferences.properties -> springEntityPairs (reference name, char code)."""
    pairs = []
    seen = {}
    for line in open(props_path, encoding="iso-8859-1").read().splitlines():
        line = line.strip()
        if not line or line.startswith("#") or line.startswith("!"):
            continue
        k, v = line.split("=", 1)
        k, v = k.strip(), v.strip()
        # java.util.Properties: later duplicate keys override earlier ones
        seen[k] = v
    assert len(set(seen.values())) == len(seen), "duplicate entity reference names"
    o = []
    o.append("// Code generated by tools/gen_tables.py from spring-web-6.0.14 HtmlCharacterEntityReferences.properties; DO NOT EDIT.\n")
    o.append("package sanitize\n")
    o.append("// springEntityRefs maps the entity name (without & and ;) to the char it stands for. The properties key is\n// the char code; the reference of key 39 is literally \"#39\".")
    o.append("var springEntityRefs = [...]struct {\n\tname string\n\tchar uint16\n}{")
    for k, v in seen.items():
        o.append('\t{"%s", %d},' % (v, int(k)))
    o.append("}")
    open(os.path.join(out_dir, "spring_gen.go"), "w", encoding="utf-8").write("\n".join(o) + "\n")


if __name__ == "__main__":
    src_dir, out_dir = sys.argv[1], sys.argv[2]
    gen_elements(src_dir, out_dir)
    gen_entities(src_dir, out_dir)
    if len(sys.argv) > 3:
        gen_spring(sys.argv[3], out_dir)
