// Dumps the java.lang.Character tables used by the OWASP lexer and by Spring's decoder (isLetter,
// isWhitespace, digit) as Go source, for the JDK that runs the reference (Java 17 = Unicode 13).
//
//	javac -d "$OUT" GenCharTables.java && java -cp "$OUT" GenCharTables > ../chars_gen.go
import java.util.ArrayList;
import java.util.List;

public class GenCharTables {
    interface Pred {
        boolean test(char c);
    }

    static void ranges(StringBuilder sb, String name, Pred p) {
        List<int[]> rs = new ArrayList<>();
        int start = -1;
        for (int c = 0; c <= 0x10000; c++) {
            boolean in = c < 0x10000 && p.test((char) c);
            if (in && start < 0) start = c;
            if (!in && start >= 0) {
                rs.add(new int[] {start, c - 1});
                start = -1;
            }
        }
        sb.append("var ").append(name).append(" = [...]uint16{\n");
        for (int[] r : rs) {
            sb.append(String.format("\t0x%04x, 0x%04x,\n", r[0], r[1]));
        }
        sb.append("}\n\n");
    }

    public static void main(String[] args) {
        StringBuilder sb = new StringBuilder();
        sb.append("// Code generated by tools/GenCharTables.java (Java ")
                .append(System.getProperty("java.version"))
                .append("); DO NOT EDIT.\n\npackage sanitize\n\n");
        sb.append("// Inclusive [lo, hi] pairs of the UTF-16 code units for which the Java predicate is true.\n\n");
        ranges(sb, "javaLetterRanges", Character::isLetter);
        ranges(sb, "javaWhitespaceRanges", Character::isWhitespace);
        // Character.digit(c, 36): value 0..35 (digits of any script, Latin letters, fullwidth letters).
        List<int[]> runs = new ArrayList<>(); // {start, count, firstValue}
        int[] cur = null;
        for (int c = 0; c < 0x10000; c++) {
            int d = Character.digit((char) c, 36);
            if (d >= 0) {
                if (cur != null && cur[0] + cur[1] == c && cur[2] + cur[1] == d) {
                    cur[1]++;
                } else {
                    cur = new int[] {c, 1, d};
                    runs.add(cur);
                }
            } else {
                cur = null;
            }
        }
        sb.append("// Runs {first code unit, length, digit value of the first} of Character.digit(c, 36) >= 0;\n");
        sb.append("// the value grows by one inside a run.\n");
        sb.append("var javaDigitRuns = [...][3]uint16{\n");
        for (int[] r : runs) {
            sb.append(String.format("\t{0x%04x, %d, %d},\n", r[0], r[1], r[2]));
        }
        sb.append("}\n");
        System.out.print(sb);
    }
}
